### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by davidt128**
Added a tiny README.md file so it is easier to understand use and implaction.

### CODE REVIEW

**Comment by isc30** [comment]
Thanks!

**Comment by isc30** [comment]
Wondering how did you find my "stream" / "tutorial" ?

**Comment by davidt128** [comment]
You put  the youtube video in the code. But if you are asking how I found this project  it was for one of my classes. Cheers!

**Comment by isc30** [comment]
Yes! haha i meant how did you found it 😃
So you are teacher?

**Comment by davidt128** [comment]
Nah, I am a student and we do stuff on github for projects/competitions to see what team can do the most.

**Pull request merged**
